### PR TITLE
Added test suite for share permission to file operations matrix

### PR DESCRIPTION
**Pull request by PVince81**
This is mostly to help me test https://github.com/owncloud/core/pull/13802 over WebDAV.

@jnfrmarks FYI

I'm still working on it / tweaking

### CODE REVIEW

**Comment by PVince81** [comment]
I'd say this is ready for review.

Note that many tests won't pass against stable7/stable8/master due to https://github.com/owncloud/core/issues/13193
Most of them are fixed by https://github.com/owncloud/core/pull/13802 but I'll try to cover the "move_XXX" ones too.

**Comment by jnfrmarks** [comment]
Test runs with the following failures:

```
2015-03-19 13:26:21,099 - ERROR - recipient_worker - Operation "rename" must be allowed when share permissions are 31
2015-03-19 13:26:21,238 - ERROR - recipient_worker - Operation "move_in" must be allowed when share permissions are 31
2015-03-19 13:26:21,379 - ERROR - recipient_worker - Operation "move_in_overwrite" must be allowed when share permissions are 31
2015-03-19 13:26:21,423 - ERROR - recipient_worker - Operation "move_in_subdir" must be allowed when share permissions are 31
2015-03-19 13:26:21,468 - ERROR - recipient_worker - Operation "move_in_subdir_overwrite" must be allowed when share permissions are 31
2015-03-19 13:26:21,513 - ERROR - recipient_worker - Operation "move_out" must be allowed when share permissions are 31
2015-03-19 13:26:21,560 - ERROR - recipient_worker - Operation "move_out_subdir" must be allowed when share permissions are 31
```

If that's expected than I give my :+1:

**Comment by PVince81** [comment]
No, this is wrong. 31 is ALL permissions, it should work.

Also you need to run the test with `-a` to make sure it uses all test cases. Not sure why this isn't the default.

**Comment by jnfrmarks** [comment]
I'm running against last night's master build and there are server errors.

From a smashbox point of view, the code looks good, though you'll want to add the log file scrape code once that gets merged.

From a server point of view, the test is finding errors.

**Comment by PVince81** [comment]
@jnfrmarks hmm now I'm seeing these errors too on my laptop (yesterday was another machine), even against the branch that "fixes everything". I'll investigate.

**Comment by PVince81** [comment]
Ah yes, of course... we need this pyocclient fix to make it work: https://github.com/owncloud/pyocclient/pull/82
Can you review it ?

**Comment by PVince81** [comment]
Without the fix there's a missing slash:

```
DAV request: MOVE /overwrite_this_through_move_in.dat
('Headers: ', {'Destination': 'http://127.0.0.1/owncloud/remote.php/webdavshared-dir/overwrite_this_through_move_in.dat'})
DAV status: 403
```

**Comment by PVince81** [comment]
The relevant PR for pyocclient was merged.

Please review this one here.

**Comment by PVince81** [comment]
@jnfrmarks the actual fix has been merged on core/master which means that these tests will pass now.
You might want to re-run this test suite and then merge it if it's ok :smile:

**Comment by jnfrmarks** [comment]
Tests pass against master.  :+1: 

I will add to the nightly run once we move over to master; for now we're against stable8.

**Pull request merged**
