### PR TITLE
Added support for increasing the number of users during a test

### PR DESCRIPTION
**Pull request by jnfrmarks**
I've added support for "share_sets" - this allows for the number of users in a test to be increased.  A "set" is the original number of users (sharer, shareeOne, shareeTwo, etc) and share_sets is the outer loop on the number of each sharer, etc.  I've only added this to test_uploadFiles.py for now.  It can be added elsewhere if others want.

@PVince81 @SergioBertolinSG @jvillafanez  for review.

### CODE REVIEW

**Comment by jnfrmarks** [comment]
@nickvergessen @MorrisJobke @PVince81 @jvillafanez @SergioBertolinSG 

Anyone to review please?

**Comment by nickvergessen** [comment]
Don't know if something is wrong on my machine, but I get

```
2015-03-26 21:11:54,110 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_1.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,113 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_2.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,137 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_3.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,146 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_4.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,183 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_5.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,186 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_6.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,193 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_7.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,194 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_8.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:54,201 - ERROR - shareeTwo01 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo01/localShareDir/TEST_FILE_NEW_USER_SHARE_9.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:56,590 - ERROR - shareeTwo02 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/shareeTwo02/localShareDir/TEST_FILE_NEW_USER_SHARE_8.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:56,789 - ERROR - sharer02 - File /home/nickv/ownCloud/Smashbox/smashdir/test_uploadFiles/sharer02/localShareDir/TEST_FILE_NEW_USER_SHARE_8.dat should exist error_check(os.path.exists(sharedFile), "File %s should exist" %sharedFile) failed in checkFilesExist() ["/home/nickv/ownCloud/Smashbox/smashbox/lib/oc-tests/test_uploadFiles.py" at line 213]
2015-03-26 21:11:58,396 - ERROR - sharer02 - 1 error(s) reported
2015-03-26 21:11:58,399 - ERROR - shareeTwo01 - 9 error(s) reported
2015-03-26 21:11:58,400 - ERROR - shareeTwo02 - 1 error(s) reported
```

**Comment by SergioBertolinSG** [comment]
When I execute the test_uploadFiles, the owncloud.log file is erased but it is not created after that so the scp commands fails while trying to get it.

The rest of the test works fine for me.

´´´
CalledProcessError: Command 'scp root@192.168.2.4:/var/www/owncloud/data/owncloud.log /home/vagrant/smashdir/test_uploadFiles/setup/.' returned non-zero exit status 1
´´´

**Comment by SergioBertolinSG** [comment]
User error.
:+1:

**Comment by jnfrmarks** [comment]
@nickvergessen 

Can I get a thumbs up?

**Pull request merged**
