### PR TITLE
clean up of some tests

### PR DESCRIPTION
**Pull request by jnfrmarks**
Cleanup up two tests.

@PVince81 @SergioBertolinSG @jvillafanez  for review.

### CODE REVIEW

**Comment by jnfrmarks** [comment]
ping

@SergioBertolinSG  @jvillafanez

**Comment by jvillafanez** [comment]
I'm not seeing anything weird. :+1:

**Comment by SergioBertolinSG** [comment]
Fine :+1:

**Comment by MorrisJobke** [comment]
@jnfrmarks What was the reason behind this?

**Comment by jnfrmarks** [comment]
@MorrisJobke 

For nplustwo, I was adding support for resetting the directories.  
For concurrentDirMove, I did a final check of the files.

This was a bit ago and these two tests were failing in my environment.  I believe that these two edits resolved the issues I was seeing.

Are you running into a problem with the edits?

**Comment by MorrisJobke** [comment]
@jnfrmarks No. I just bring stuff to upstream, and wondered if this is also worth to port to upstream.

**Comment by jnfrmarks** [comment]
I'm not sure - my changes may not be relevant to CERN or, I may have made them in error ;)

edit: Or they may have fixed what I was seeing

**Pull request merged**
