### PR TITLE
Fix the version comparison for alpha/beta/rc

### PR DESCRIPTION
**Pull request by nickvergessen**
@ckamm should fix your version problems.

### CODE REVIEW

**Comment by ckamm** [comment]
@nickvergessen Should this PR target cernbox/smashbox?

**Comment by nickvergessen** [comment]
No, I will update the cernbox PR in a bit.

**Comment by nickvergessen** [comment]
@ckamm thanks for the hint with tuple comparison, I now made strings negative integers in the tuple, so tuple comparison passes correctly for those.

And since I didn't touch the test cases it behaves the same as before :)

**Comment by nickvergessen** [comment]
Also sent to cernbox in https://github.com/cernbox/smashbox/pull/60

**Comment by nickvergessen** [comment]
@PVince81 mind reviewing, so we can merge?

I ran our tests that use the method and they still pass.

**Comment by ckamm** [comment]
@nickvergessen :+1:

**Comment by PVince81** [comment]
:+1:

**Pull request merged**
