### PR TITLE
Sharing 2.0

### PR DESCRIPTION
**Pull request by nickvergessen**
Should be sent against cern in the end, but for now let's do it here.

### CODE REVIEW

**Comment by nickvergessen** [comment]
The failing tests case is due to a change in the error message:
- 8.2
  
  > Status code: 403
  > Message: You are not allowed to share /TEST_FILE_USER_RESHARE.dat/
- 9.0
  
  > Status code: 404
  > Message: Path is not shareable

I think the 404 is a mistake and it should in fact be 403, because the resource exists, its just forbidden to do it...

**Comment by nickvergessen** [comment]
@rullzer see above

I can easily fix the smashbox assertion, but we need to be sure that the API change is intended

**Comment by rullzer** [comment]
:+1: thanks :)

**Comment by DeepDiver1975** [comment]
> but we need to be sure that the API change is intended

NO - please no API change!

This is a breakage we cannot accept!

**Comment by nickvergessen** [comment]
The API change (status code) was fixed (reverted), as it was unintended ;)

**Comment by nickvergessen** [comment]
And that was in the core PR, not here.

**Comment by DeepDiver1975** [comment]
> And that was in the core PR, not here.

as a result this pr is not required - right?

**Comment by nickvergessen** [comment]
No, this PR is required, because of the change how reshares are (not) deleted?

**Comment by DeepDiver1975** [comment]
> No, this PR is required, because of the change how reshares are (not) deleted?

ah - this is for reshare - thanks!

**Comment by nickvergessen** [comment]
Okay, no response from cern so far, so lets fix it on our side and then I will resolve the conflict, when they merged it.

**Comment by nickvergessen** [comment]
Upstream PR https://github.com/cernbox/smashbox/issues/60

**Pull request merged**
