### PR TITLE
Locking tests overwrites

### PR DESCRIPTION
**Pull request by jvillafanez**
Add a bunch of tests for overwrite + locking

### CODE REVIEW

**Comment by jvillafanez** [comment]
@nickvergessen @PVince81 @jnfrmarks  This add new tests into the "locking_tests" branch.

There are currently 2 tests commented: upload with chunks and zip downloads. I expect to add those test "officially" when their issues are solved.

**Comment by nickvergessen** [comment]
btw we can keep the PRs seperated, there is no need to merge them in local branches before we get them into master...?

**Comment by jvillafanez** [comment]
There was some dependency between the branches so better branch from the locking_tests and merge back to it.

I prefer having all the locking tests in one branch, even though it's not in the master branch. New tests for locking can use this base branch to have all the locking code up to date if needed

**Comment by nickvergessen** [comment]
why was this merged, please read emails :angry:

**Comment by jvillafanez** [comment]
It's merged against the locking_tests branch. Think about it as adding more tests to the locking_tests PR. The ongoing work in the master branch shouldn't be affected.

I'll take care of updating the locking_tests branch with the master code when it's ready.

**Comment by nickvergessen** [comment]
Ah right, didn't see the target branch, sorry for the noise :speak_no_evil:

**Pull request merged**
