### PR TITLE
specify that we want python2

### PR DESCRIPTION
**Pull request by icewind1991**
For those distro's that default to python3

cc @MorrisJobke

### CODE REVIEW

**Comment by jnfrmarks** [comment]
@icewind1991 

Did you run a test to validate the change doesn't introduce any issues?  If so, then I give my :+1:

**Comment by icewind1991** [comment]
I need those changes to get it running in the first place, someone with a distro which defaults to python2 (most of them) should verify that stuff still works

**Comment by MorrisJobke** [comment]
:+1:

**Comment by MorrisJobke** [comment]
@jnfrmarks Can you provide an upstream patch for this?

**Comment by jnfrmarks** [comment]
@MorrisJobke 

I don't know what you mean ;)

**Comment by MorrisJobke** [comment]
@jnfrmarks I will do :)

**Comment by MorrisJobke** [comment]
Once it is merged ;)

**Comment by jnfrmarks** [comment]
:+1: 

Talked with @icewind1991 and he tested this locally to his branch.  I'm good with that :)

**Comment by MorrisJobke** [comment]
Upstream: https://github.com/cernbox/smashbox/pull/7

**Pull request merged**
