### PR TITLE
updated with new install instructions

### PR DESCRIPTION
**Pull request by jnfrmarks**
updated readme.md file.

@PVince81 @SergioBertolinSG  for review

### CODE REVIEW

**Comment by SergioBertolinSG** [comment]
For me the install of requirements doesn't work:

```
[vagrant@localhost smashbox]$ sudo pip install -r requirements.txt 
Obtaining pyocclient from git+git@github.com:owncloud/pyocclient.git@master#egg=pyocclient (from -r requirements.txt (line 1))
  Cloning git@github.com:owncloud/pyocclient.git (to master) to ./src/pyocclient
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
  Complete output from command /bin/git clone -q git@github.com:owncloud/pyocclient.git /home/vagrant/SERGIO/smashbox/src/pyocclient:

----------------------------------------
Cleaning up...
Command /bin/git clone -q git@github.com:owncloud/pyocclient.git /home/vagrant/SERGIO/smashbox/src/pyocclient failed with error code 128 in None
```

Just this command alone is not working:

```
git clone -q git@github.com:owncloud/pyocclient.git
```

Does it work for you?

**Comment by PVince81** [comment]
Does `git clone https://github.com/owncloud/pyocclient.git` work for you ?

**Comment by jnfrmarks** [comment]
I needed to update my rsa key to get this to work.

**Comment by SergioBertolinSG** [comment]
@PVince81 Yes, that works fine

**Comment by PVince81** [comment]
@jnfrmarks we might want to use the read-only URL "https://github.com/owncloud/pyocclient.git" instead, because that would work for anybody, even people without Github accounts/keys.

**Comment by jnfrmarks** [comment]
I updated the requirements.txt file.

**Comment by SergioBertolinSG** [comment]
:+1:

**Pull request merged**
