### PR TITLE
Add file name patterns excluded by the sync client

### PR DESCRIPTION
**Pull request by PVince81**
Added a few file name patterns that we know the sync client will
exclude. This reduces the number of failing cases.

Partial fix for test_filenames.
The other fixes need to be put on core/master because they were real issues.

@jnfrmarks @SergioBertolinSG

(we might want to send a PR to cernbox as well)

### CODE REVIEW

**Comment by PVince81** [comment]
Related to https://github.com/owncloud/smashbox/issues/21

**Comment by PVince81** [comment]
Note: I didn't add the empty space `" "` because the sync client does send a request to the server, but the server responds with 400 Bad Request. This is to be handled differently I guess (either the sync client must exclude file names containing only spaces or the server needs to accept such names)

**Comment by jnfrmarks** [comment]
:+1:

**Comment by MorrisJobke** [comment]
upstream cernbox/smashbox#5

**Pull request merged**
