### PR TITLE
Check syntax of .py files on travis

### PR DESCRIPTION
**Pull request by nickvergessen**
demo of a syntax broken run:
https://travis-ci.org/owncloud/smashbox/builds/62710918

### CODE REVIEW

**Comment by nickvergessen** [comment]
Let's make travis a simple syntax check, so the PRs are green instead of read.

@PVince81

**Comment by PVince81** [comment]
It's a good start. :smile: 

:+1:

**Comment by PVince81** [comment]
@jnfrmarks what do you think ?

**Comment by DeepDiver1975** [comment]
:+1:

**Pull request merged**
