### PR TITLE
Login new users to generate their encryption keys

### PR DESCRIPTION
**Pull request by nickvergessen**
This makes the following tests pass with encryption:
- **test_reshareDir.py**
- **test_shareFile.py** (requires core PR to fix with and without encryption: https://github.com/owncloud/core/pull/16159 )
- **test_uploadFiles.py**

@jnfrmarks @SergioBertolinSG please review

PS: should go upstream once merged here

### CODE REVIEW

**Comment by jnfrmarks** [comment]
The login bits seem to work but the test is failing with this in the log file:

```

{"reqId":"wIQB02xT42yvg+XJaX88","remoteAddr":"172.18.5.197","app":"PHP","message":"fopen(\/var\/www\/html\/owncloud\/data\/user2): failed to open stream: Is a directory at \/var\/www\/html\/owncloud\/apps\/files_locking\/lib\/lock.php#134","level":3,"time":"2015-05-07T19:57:10+00:00"}
{"reqId":"wIQB02xT42yvg+XJaX88","remoteAddr":"172.18.5.197","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Target file  is locked by another process.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #30)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('TEST_FILE_MODIF...', Resource id #30, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(84): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":174}","level":4,"time":"2015-05-07T19:57:10+00:00"}

```

Also in core at https://github.com/owncloud/core/issues/16182

**Comment by nickvergessen** [comment]
I'm currently testing without files locking.

Only trashbin, versions, sharing, provisioning (and encryption)

Which test is failing for you?

**Comment by jnfrmarks** [comment]
I'm not sure: it was one of the three above ;)

Edit: Ah! I wrote the test name in the core issue: test_shareFile.py

**Comment by nickvergessen** [comment]
Did you have the core PR merged that is specified ?

**Comment by jnfrmarks** [comment]
@nickvergessen 

The description refers to the core issue which morphed into a files_locking issue: https://github.com/owncloud/files_locking/issues/24.

**Comment by nickvergessen** [comment]
No, files_locking shall be disabled as for now. The issue mentioned is https://github.com/owncloud/core/pull/16159 which was merged. so please retry ;)

**Comment by nickvergessen** [comment]
Cern PR https://github.com/cernbox/smashbox/pull/22

**Pull request merged**
